import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <button
        id='mybutton'
        onClick={()=>{
          console.log("hello")
          window.parent.postMessage('any message', "*");
          if(window.flutter_inappwebview) {
            window.flutter_inappwebview.callHandler('myHandlerName', 'click from my button');
          } else {
            console.log('not able to find button')
          }
        }}
        >Hello</button>
       </main>
    </div>
  )
}
